spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useSSL=false
    username: root
    password: PasswordforMySQL.2022
  jpa:
    hibernate:
      ddl-auto: none


sites:
  - url: https://www.nikoartgallery.com/
    name: Галерея и креативное пространство Нико
  #- url: http://www.playback.ru/
   # name: Интернет магазин PlayBack.ru
  - url: http://www.aot.ru/
    name: Автоматическая обработка текста
  #user-agent: AdvancedSearchBot
  #web-interface-path: /admin